apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dsx-connect-api
  namespace: dsx-connect
spec:
  ingressClassName: traefik
  rules:
    - host: dsx-connect.10.2.4.103.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dsx-connect-api
                port:
                  number: 8091
