apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dsxa-scanner
  namespace: dsx-connect
spec:
  ingressClassName: traefik
  rules:
    - host: dsxa-scanner.10.2.4.103.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dsxa-scanner
                port:
                  number: 15000
